### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ApoorvGuptaAi** [ApoorvGuptaAi/iitk-india-covid-data-parser#1]
[ERROR] ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 122, in lambda_handler
    return main(event)
  File "/var/task/lambda_function.py", line 86, in main
    url_hospitals_map = get_ap_hospitals()
  File "/var/task/ap_official_parser.py", line 59, in get_ap_hospitals
    district_map = get_district_post_params(scraped_data)
  File "/var/task/ap_official_parser.py", line 25, in get_district_post_params
    output = {x.split('=')[0]:int(x.split('=')[1]) for x in params.split("&")}
  File "/var/task/ap_official_parser.py", line 25, in <dictcomp>
    output = {x.split('=')[0]:int(x.split('=')[1]) for x in params.split("&")}

**Comment by srd** [comment]
Yeah, the issue is happening because the AP website is returning table data in malformed way. Hoping they fix it and this resolves. If not - will go ahead and update the parser to understand the incorrect input.
