### ISSUE TITLE
West Bengal parser failing

### ISSUE THREAD

**Issue by ApoorvGuptaAi** [ApoorvGuptaAi/iitk-india-covid-data-parser#4]
[ERROR] ValueError: invalid literal for int() with base 10: '...'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 143, in lambda_handler
    return main(event)
  File "/var/task/lambda_function.py", line 107, in main
    url_hospitals_map = get_west_bengal_data(district_filter)
  File "/var/task/west_bengal_parser.py", line 175, in get_hospital_data
    return WestBengalParser.export_hospital_data(districts)
  File "/var/task/west_bengal_parser.py", line 169, in export_hospital_data
    west_bengal_parser = WestBengalParser().parse_hospitals(districts)
  File "/var/task/west_bengal_parser.py", line 70, in parse_hospitals
    pages = [x for x in range(1, int(pagination.find_all('a')[-1].get_text()) + 1)]

**Comment by sunbrst** [comment]
I know how to fix this...taking care of it

**Comment by sunbrst** [comment]
Should be fixed in e11cd04ee8eba114b2a4910d59cdac7dc952ae8b @ApoorvGuptaAi

**Comment by ApoorvGuptaAi** [comment]
Thanks @sunbrst
